name: Build Dist on Push
on:
  push:
    branches:
      - gh-pages # 或者你的代码所在的其他分支
jobs:
  build-dist:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup_node@v3
        with:
          node-version: '14.18.0' # 根据你的项目需求选择节点版本
      - name: Install dependencies
        run: npm install
      - name: Build dist
        run: npm run build # 假设你的构建命令是 'npm run build'，如果不同请修改